pharmacies/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from pharmacies import settings
from shop import views

schema_view = get_schema_view(
    openapi.Info(
        title="Pharmacies API",
        default_version='v0.1',
        description="Our API!",
        terms_of_service="https:/farmacie.pythonanywhere.com",
        contact=openapi.Contact(email="contact@farmacie.pythonanywhere.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
                  path('', views.homepage, name='home'),
                  path('admin/', admin.site.urls),
                  path('api-auth/', include('rest_framework.urls')),
                  url(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
                  url(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
                  path('authentication/', include('authentication.urls')),
                  path('shop/', include('shop.urls')),
                  path('timetable/', include('timetable.urls')),
                  path('transfer/', include('transfer.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.sites.AdminSite.site_header = 'Medical Store Admin Panel'
admin.sites.AdminSite.site_title = 'Medical Store Admin Panel'
admin.sites.AdminSite.index_title = 'Admin'

shop/urls.py
from django.urls import path, include
from rest_framework import routers

from shop import views

app_name = 'shop'

router = routers.DefaultRouter()
router.register(r'pharmacy/api', views.PharmacyViewSet, basename='pharmacyapi')
router.register(r'category/api', views.CategoryViewSet, basename='categoryapi')
router.register(r'product/api', views.ProductViewSet, basename='productapi')
router.register(r'buyer/api', views.BuyerViewSet, basename='buyerapi')
router.register(r'review/api', views.ReviewViewSet, basename='reviewapi')
router.register(r'contact/api', views.ContactViewSet, basename='contactapi')

urlpatterns = [
    path('', views.homepage, name='home'),
    path(r'', include(router.urls)),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name="contact"),
    path('pharmacies/', views.pharmacy_list, name='pharmacies_list'),
    path('pharmacies/<id>/', views.pharmacy_detail, name='pharmacies_detail'),
    path('categories/<slug>/', views.categories, name='categories'),
    path('products/', views.product_list, name='products_list'),
    path('products/<id>', views.product_detail, name='products_detail'),
    path('search/', views.search, name='search'),
    path('sellproduct/', views.sell_product, name='sell_product'),
    path('buyitems/', views.buy_items, name='buy_items'),
    path('cart/', views.cart, name='cart'),
    path('resetcart/', views.reset_cart, name='reset_cart'),
    path('payment/', views.payment, name='payment'),
    path('checkout/', views.checkout, name="checkout"),
    path('<id>/addcart/', views.add_cart, name='add_cart'),
    path('<id>/addreview/', views.add_review, name='add_review'),
]

timetable/urls.py
from django.urls import path, include
from rest_framework import routers

from timetable import views

app_name = 'timetable'

router = routers.DefaultRouter()
router.register(r'timetable/api', views.TimetableViewSet, basename='timetableapi')

urlpatterns = [
    path('', views.homepage, name='home'),
    path(r'', include(router.urls)),
    path('timetable/', views.view, name='view_timetable'),
    path('timetable/calc', views.calculate, name='calc_timetable'),
]

timetable/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

from shop.models import Pharmacy
from timetable import choices


class Timetable(models.Model):
    id = models.AutoField(primary_key=True)
    pharmacy = models.ForeignKey(Pharmacy, on_delete=models.CASCADE)

    day = models.CharField(max_length=250, choices=choices.day_choices, blank=True)
    slot4h = models.IntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(6)])
    active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "Timetable " + self.id.__str__() + " - " + self.pharmacy.__str__() + " - " + self.day.__str__() + " S" + self.slot4h.__str__()

    class Meta:
        verbose_name_plural = "Timetables"

timetable/views.py
import logging
import math
import random

from django.contrib import messages
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from rest_framework import viewsets

from pharmacies import settings
from pharmacies.permission import IsAdminOrReadOnly
from shop.models import Category, Product, Pharmacy
from timetable.models import Timetable
from timetable.serializer import TimetableSerializer

logger = logging.getLogger("mylogger")


def homepage(request):
    products_all = Product.objects.filter(active=True)
    categories = Category.objects.filter(active=True)
    products = Product.objects.filter(active=True).order_by('-created')
    featured_products = Product.objects.filter(featured=True)
    paginator = Paginator(products, 6)
    page = request.GET.get('page')
    products = paginator.get_page(page)
    return render(request, 'shop/base.html',
                  {'products_all': products_all, 'categories': categories, 'product': products,
                   'featured_products': featured_products})


def view(request):
    days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
    array = [1, 2, 3, 4, 5, 6]
    slots = Timetable.objects.order_by('day', 'slot4h')
    return render(request, 'timetable/timetable.html', {'slots': slots, 'days': days, 'array': array})


def calculate(request):
    count = Pharmacy.objects.all().count()

    if not request.user.is_superuser:
        messages.info(request, 'You have to logged as admin in first to calculate the timetable')
        return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))
    elif count < 3:
        messages.error(request, 'Three pharmacies are needed in order to calculate the timetable')
        return redirect('timetable:view_timetable')
    else:
        algorithm_timetable(request)  # Chiamata algorithm_timetable()
        messages.success(request, 'Timetable calculated!')
        return redirect('timetable:view_timetable')


def algorithm_timetable(request):
    # Vettori paralleli
    itemsFarmacie = Pharmacy.objects.all()

    itemSlotMin = []

    for f in itemsFarmacie:
        itemSlotMin.append(f.getSlot4hMinWeek())

    SummSlotMin = sum(itemSlotMin)

    Timetable.objects.all().delete()  # Svuotare le istanze di Timetable

    if SummSlotMin == 42:  ### CASO: SE ABBIAMO ESATTAMENTE 42 SLOT DA RIEMPIRE
        K = list(range(0, 42))
        i = 0
        for farm in itemsFarmacie:  # Per ogni farmacia
            slotmin = itemSlotMin[i]

            for j in range(slotmin):  # Per ogni suo slot
                s = int(random.choice(K))
                insert(s, farm)
                K.remove(s)
            # END FOR
            i = i + 1
        # END FOR
    # END IF

    elif SummSlotMin > 42:  ### CASO: SE ABBIAMO PIU DI 42, AVREMO DELLE SOVRAPPOSIZIONI
        i = 0
        contatore = 0
        K = list(range(0, 42))

        for farm in itemsFarmacie:  # Per ogni farmacia
            slotmin = itemSlotMin[i]

            for j in range(slotmin):  # Per ogni suo slot
                if contatore < 42:  # PRIMA EFFETTUO I RIEMPIMENTI OBBLIGATORI, POI QUELLI PER SOVRAPPOSIZIONI
                    s = int(random.choice(K))
                    insert(s, farm)
                    K.remove(s)
                    contatore = contatore + 1

                else:
                    CTT = 0
                    LISTRND = list(range(1, 11))
                    while len(LISTRND) > 0 and CTT == 0:

                        p = random.choice(LISTRND)
                        if p == 1:
                            numberList = [0, 6, 12, 18, 24, 30, 36]
                            w = 1
                            CT = 0
                            while CT == 0 and len(numberList) > 0:
                                s = random.choice(numberList)
                                G = calcolagiorno(s)
                                tupla = Timetable.objects.filter(pharmacy=farm.id, day=G, slot4h=w)
                                if len(tupla) == 0:
                                    CT = 1
                                    insert(s, farm)
                                    CTT = 1
                                numberList.remove(s)
                            LISTRND.remove(1)
                        elif p == 2:
                            numberList = [1, 7, 13, 19, 25, 31, 37]
                            w = 2
                            CT = 0
                            while CT == 0 and len(numberList) > 0:
                                s = random.choice(numberList)
                                G = calcolagiorno(s)
                                tupla = Timetable.objects.filter(pharmacy=farm.id, day=G, slot4h=w)
                                if len(tupla) == 0:
                                    CT = 1
                                    insert(s, farm)
                                    CTT = 1
                                numberList.remove(s)
                            LISTRND.remove(2)

                        elif p >= 3 and p < 6:
                            numberList = [2, 8, 14, 20, 26, 32, 38]
                            w = 3
                            CT = 0
                            while CT == 0 and len(numberList) > 0:
                                s = random.choice(numberList)
                                G = calcolagiorno(s)
                                tupla = Timetable.objects.filter(pharmacy=farm.id, day=G, slot4h=w)
                                if len(tupla) == 0:
                                    CT = 1
                                    insert(s, farm)
                                    CTT = 1
                                numberList.remove(s)
                            LISTRND.remove(3)
                            LISTRND.remove(4)
                            LISTRND.remove(5)

                        elif p >= 6 and p < 9:
                            numberList = [3, 9, 15, 21, 27, 33, 39]
                            w = 4
                            CT = 0
                            while CT == 0 and len(numberList) > 0:
                                s = random.choice(numberList)
                                G = calcolagiorno(s)
                                tupla = Timetable.objects.filter(pharmacy=farm.id, day=G, slot4h=w)
                                if len(tupla) == 0:
                                    CT = 1
                                    insert(s, farm)
                                    CTT = 1
                                numberList.remove(s)
                            LISTRND.remove(6)
                            LISTRND.remove(7)
                            LISTRND.remove(8)

                        elif p == 9:
                            numberList = [4, 10, 16, 22, 28, 34, 40]
                            w = 5
                            CT = 0
                            while CT == 0 and len(numberList) > 0:
                                s = random.choice(numberList)
                                G = calcolagiorno(s)
                                tupla = Timetable.objects.filter(pharmacy=farm.id, day=G, slot4h=w)
                                if len(tupla) == 0:
                                    CT = 1
                                    insert(s, farm)
                                    CTT = 1
                                numberList.remove(s)
                            LISTRND.remove(9)

                        else:
                            numberList = [5, 11, 17, 23, 29, 35, 41]
                            w = 6
                            CT = 0
                            while CT == 0 and len(numberList) > 0:
                                s = random.choice(numberList)
                                G = calcolagiorno(s)

                                tupla = Timetable.objects.filter(pharmacy=farm.id, day=G, slot4h=w)
                                if len(tupla) == 0:
                                    CT = 1
                                    insert(s, farm)
                                    CTT = 1
                                numberList.remove(s)

                            LISTRND.remove(10)
            # END FOR
            i = i + 1
        # END FOR

    else:  ### CASO: SE ABBIAMO MENO DI 42 SLOT, DEVO FORZARE ALCUNE/TUTTE LE FARMACIE A TENERE APERTO PIU DEGLI SLOT MINIMI
        K = list(range(0, 42))

        i = 0
        for farm in itemsFarmacie:  # Per ogni farmacia
            slotmin = itemSlotMin[i]

            for j in range(slotmin):  # Per ogni suo slot
                s = int(random.choice(K))
                insert(s, farm)
                K.remove(s)

            # END FOR
            i = i + 1
        # END FOR

        while len(K) > 0:
            x = random.choice(K)

            if x < 10:
                itemsFarmacieOrdered = Pharmacy.objects.all().order_by('-slot4hMinWeek')[0]
                insert(K[0], itemsFarmacieOrdered)
                K.pop(0)

            elif x >= 10 and x < 40:
                itemsFarmacieOrdered = Pharmacy.objects.all().order_by('-slot4hMinWeek')[1]
                insert(K[0], itemsFarmacieOrdered)
                K.pop(0)

            else:
                itemsFarmacieOrdered = Pharmacy.objects.all().order_by('-slot4hMinWeek')[2]
                insert(K[0], itemsFarmacieOrdered)
                K.pop(0)
        # END WHILE


def calcolagiorno(p):
    giorno = (math.trunc(p // 6) + 1)

    # Scelta del giorno della settimana
    if giorno == 1:
        G = "Monday"
    elif giorno == 2:
        G = "Tuesday"
    elif giorno == 3:
        G = "Wednesday"
    elif giorno == 4:
        G = "Thursday"
    elif giorno == 5:
        G = "Friday"
    elif giorno == 6:
        G = "Saturday"
    else:
        G = "Sunday"
    return G


def insert(t, farmacia):
    G = calcolagiorno(t)

    # Scelta dello slot

timetable/templates/timetable/timetable.html
{% extends "shop/base.html" %}
{% load bootstrap4 %}
<title>{% block title %}Timetable{% endblock %}</title>

{% block content %}

    <center>
        {% bootstrap_messages %}
        <br>
        <div class="container">
            <h3>Timetable</h3>
        </div>
    </center>
    <br>
    <center>
        <div style="width: 75%;">
            <table table class="table" width="75%">
                <tr>
                    <th>
                        <center>TIMETABLE</center>
                    </th>
                    <th>
                        <center>0 - 4</center>
                    </th>
                    <th>
                        <center>4 - 8</center>
                    </th>
                    <th>
                        <center>8 - 12</center>
                    </th>
                    <th>
                        <center>12 - 16</center>
                    </th>
                    <th>
                        <center>16 - 20</center>
                    </th>
                    <th>
                        <center>20 - 24</center>
                    </th>
                </tr>

                <tr>
                    <th>
                        <center>Monday</center>
                    </th>
                    {% for i in array %}
                        <td>
                            {% for slot in slots %}
                                {% if 'Monday' == slot.day and i == slot.slot4h %}
                                    <center>
                                        <a href="{% url 'shop:pharmacies_detail' slot.pharmacy.id %}"
                                           class="btn btn-primary">{{ slot.pharmacy.name }}</a>
                                        <br><br>
                                    </center>
                                {% endif %}
                            {% endfor %}
                        </td>
                    {% endfor %}
                </tr>

                <tr>
                    <th>
                        <center>Tuesday</center>
                    </th>
                    {% for i in array %}
                        <td>
                            {% for slot in slots %}
                                {% if 'Tuesday' == slot.day and i == slot.slot4h %}
                                    <center>
                                        <a href="{% url 'shop:pharmacies_detail' slot.pharmacy.id %}"
                                           class="btn btn-primary">{{ slot.pharmacy.name }}</a>
                                        <br><br>
                                    </center>
                                {% endif %}
                            {% endfor %}
                        </td>
                    {% endfor %}
                </tr>

                <tr>
                    <th>
                        <center>Wednesday</center>
                    </th>
                    {% for i in array %}
                        <td>
                            {% for slot in slots %}
                                {% if 'Wednesday' == slot.day and i == slot.slot4h %}
                                    <center>
                                        <a href="{% url 'shop:pharmacies_detail' slot.pharmacy.id %}"
                                           class="btn btn-primary">{{ slot.pharmacy.name }}</a>
                                        <br><br>
                                    </center>
                                {% endif %}
                            {% endfor %}
                        </td>
                    {% endfor %}
                </tr>

                <tr>
                    <th>
                        <center>Thursday</center>
                    </th>
                    {% for i in array %}
                        <td>
                            {% for slot in slots %}
                                {% if 'Thursday' == slot.day and i == slot.slot4h %}
                                    <center>
                                        <a href="{% url 'shop:pharmacies_detail' slot.pharmacy.id %}"
                                           class="btn btn-primary">{{ slot.pharmacy.name }}</a>
                                        <br><br>
                                    </center>
                                {% endif %}
                            {% endfor %}
                        </td>
                    {% endfor %}
                </tr>

                <tr>
                    <th>
                        <center>Friday</center>
                    </th>
                    {% for i in array %}
                        <td>
                            {% for slot in slots %}
                                {% if 'Friday' == slot.day and i == slot.slot4h %}
                                    <center>
                                        <a href="{% url 'shop:pharmacies_detail' slot.pharmacy.id %}"
                                           class="btn btn-primary">{{ slot.pharmacy.name }}</a>
                                        <br><br>
                                    </center>
                                {% endif %}
                            {% endfor %}
                        </td>
                    {% endfor %}
                </tr>

                <tr>
                    <th>
                        <center>Saturday</center>
                    </th>
                    {% for i in array %}
                        <td>
                            {% for slot in slots %}
                                {% if 'Saturday' == slot.day and i == slot.slot4h %}
                                    <center>
                                        <a href="{% url 'shop:pharmacies_detail' slot.pharmacy.id %}"
                                           class="btn btn-primary">{{ slot.pharmacy.name }}</a>
                                        <br><br>
                                    </center>
                                {% endif %}
                            {% endfor %}
                        </td>
                    {% endfor %}
                </tr>

                <tr>
                    <th>
                        <center>Sunday</center>
                    </th>
                    {% for i in array %}
                        <td>
                            {% for slot in slots %}
                                {% if 'Sunday' == slot.day and i == slot.slot4h %}
                                    <center>
                                        <a href="{% url 'shop:pharmacies_detail' slot.pharmacy.id %}"
                                           class="btn btn-primary">{{ slot.pharmacy.name }}</a>
                                        <br><br>
                                    </center>
                                {% endif %}
                            {% endfor %}
                        </td>
                    {% endfor %}
                </tr>
            </table>
        </div>
    </center>
{% endblock %}